# Generated by Django 4.0.3 on 2022-03-26 00:20

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitmembro',
            name='data_aniversario',
            field=models.DateField(default='01/01/2000', verbose_name='Data de Aniversário'),
        ),
        migrations.AlterField(
            model_name='visitmembro',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, default=1, upload_to=core.models.get_file_path, verbose_name='Imagem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitmembro',
            name='primeira_visita',
            field=models.DateField(default='01/01/2000', verbose_name='Data da Primeira Visita'),
        ),
    ]
