# Generated by Django 4.0.3 on 2022-03-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_visitmembro_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='visitmembro',
            name='departamentos',
            field=models.ManyToManyField(to='core.departamento'),
        ),
    ]
