# Generated by Django 4.0.3 on 2022-03-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='primeira_visita',
            field=models.DateField(auto_now=True, verbose_name='Data da Primeira Visita'),
        ),
    ]
