# Generated by Django 4.0.3 on 2022-03-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_customusuario_primeira_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='data_aniversario',
            field=models.DateField(default='2000-01-01', verbose_name='Data de Aniversário'),
        ),
    ]
